version: 2.1

orbs:
  circleci-orb-test: mattwelke/circleci-orb-test@0.0.1

jobs:
  test-orb:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Do something before using the orb
          command: |
            echo "Here we go... about to use the orb..."
      - circleci-orb-test/greet:
          subject: CircleCI
      - run:
          name: Do something after using the orb
          command: |
            echo "Hopefully that worked!"

workflows:
  test-orb:
    jobs:
      - test-orb
