version: 2.1

orbs:
  circleci-orb-test: mattwelke/circleci-orb-test@0.0.18

jobs:
  test-orb:
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8085
      GOOGLE_CLOUD_PROJECT: test-project
      DOCKER_HUB_ID: mwelke

    docker:
      - image: cimg/node:14.14.0
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
      - image: google/cloud-sdk:313.0.0
        command: gcloud beta emulators pubsub start --project=test-project
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD

    resource_class: small

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Node.js test before using the orb
          command: |
            npm test
      - circleci-orb-test/greet:
          subject: CircleCI
      - setup_remote_docker:
            docker_layer_caching: false
      - circleci-orb-test/build-and-push-to-docker-hub:
          docker-hub-id: $DOCKER_HUB_ID
          docker-hub-password: DOCKER_HUB_PASSWORD
          image: $DOCKER_HUB_ID/circleci-orb-user-test

workflows:
  test-orb:
    jobs:
      - test-orb
