version: 2.1

orbs:
  circleci-orb-test: mattwelke/circleci-orb-test@0.0.14

jobs:
  test-orb:
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8085
      GOOGLE_CLOUD_PROJECT: test-project

    docker:
      - image: cimg/node:14.14.0
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
      - image: google/cloud-sdk:313.0.0
        command: gcloud beta emulators pubsub start --project=test-project
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD

    resource_class: small

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Node.js test before using the orb
          command: |
            npm test
      - circleci-orb-test/greet:
          subject: CircleCI
      - setup_remote_docker:
            docker_layer_caching: false
      - circleci-orb-test/build-and-push-docker:
          docker-hub-id: DOCKER_HUB_ID
          docker-hub-password: DOCKER_HUB_PASSWORD
          test-env-var-param: TEST_ENV_VAR_PARAM
          repo: circleci-orb-user-test
          tag: << pipeline.git.revision >>
      # - run:
      #     name: Auth with Docker Hub
      #     command: |
      #       echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_ID --password-stdin
      # - run:
      #     name: Build app
      #     command: |
      #       docker build -t $DOCKER_HUB_ID/circleci-orb-user-test:<< pipeline.git.revision >> .
      # - run:
      #     name: Push build
      #     command: |
      #       docker push $DOCKER_HUB_ID/circleci-orb-user-test:<< pipeline.git.revision >>

workflows:
  test-orb:
    jobs:
      - test-orb
