version: 2.1

orbs:
  circleci-orb-test: mattwelke/circleci-orb-test@0.0.7

jobs:
  test-orb:
    environment:
      PUBSUB_EMULATOR_HOST: localhost:8538
      PUBSUB_EMULATOR_PROJECT: test-project
      GOOGLE_CLOUD_PROJECT: test-project

    docker:
      - image: cimg/node:14.14.0
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD
      - image: google/cloud-sdk:313.0.0
        command: gcloud beta emulators pubsub start
        auth:
          username: $DOCKER_HUB_ID
          password: $DOCKER_HUB_PASSWORD

    resource_class: small

    steps:
      - checkout
      - run: npm ci
      - run:
          name: Run Node.js test before using the orb
          command: |
            npm test
      - circleci-orb-test/greet:
          subject: CircleCI
      - run:
          name: Do something after using the orb
          command: |
            echo "Hopefully that worked!"

workflows:
  test-orb:
    jobs:
      - test-orb
