version: 2.1

orbs:
  circleci-orb-test: mattwelke/circleci-orb-test@0.0.2

jobs:
  test-orb:
    executor:
      name: circleci-orb-test/default
      docker-hub-id: DOCKER_HUB_ID_MY_APP
      docker-hub-password: DOCKER_HUB_PASSWORD_MY_APP

    steps:
      - run:
          name: Do something before using the orb
          command: |
            echo "Here we go... about to use the orb..."
      - circleci-orb-test/greet:
          subject: CircleCI
      - run:
          name: Do something after using the orb
          command: |
            echo "Hopefully that worked!"

workflows:
  test-orb:
    jobs:
      - test-orb
